{% set name = "apache-airflow-providers-apache-flink" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_apache_flink-{{ version }}.tar.gz
  sha256: d2fc5c23887f78f23168e1bfea5fddd6bc905ebde8642957431480d778a0e84c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow-providers-cncf-kubernetes >=5.1.0
    - apache-airflow >=2.8.0
    - cryptography >=41.0.0

test:
  imports:
    - airflow.providers.apache.flink
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-apache-flink for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/apache/flink/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-flink/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
